services:
  db:
    build:
      context: .
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - data
    volumes:
      - ./src:/var/lib/postgresql
networks:
  data:
